//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buses.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public A_Customer()
        {
            this.Online_Ticketing = new HashSet<Online_Ticketing>();
            this.Customer_Booking = new HashSet<Customer_Booking>();
            this.CustomerNOKs = new HashSet<CustomerNOK>();
        }
    
        public int Customer_ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Telephone { get; set; }
        public string Gender { get; set; }
        public string Nationality { get; set; }
        public string User_Id { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
    
        public virtual A_Country A_Country { get; set; }
        public virtual A_Gender A_Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Online_Ticketing> Online_Ticketing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_Booking> Customer_Booking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerNOK> CustomerNOKs { get; set; }
    }
}
