//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buses.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public A_Employees()
        {
            this.A_Buses = new HashSet<A_Buses>();
            this.Employee_NOK = new HashSet<Employee_NOK>();
            this.Educations = new HashSet<Education>();
        }
    
        public int Employee_ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Telephone { get; set; }
        public string NIN_No { get; set; }
        public string Gender { get; set; }
        public string Nationality { get; set; }
        public Nullable<int> Company { get; set; }
        public Nullable<int> Title { get; set; }
        public string User_Id { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> EditionDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A_Buses> A_Buses { get; set; }
        public virtual A_Companies A_Companies { get; set; }
        public virtual A_Country A_Country { get; set; }
        public virtual A_Gender A_Gender { get; set; }
        public virtual A_Personel_Titles A_Personel_Titles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_NOK> Employee_NOK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Education> Educations { get; set; }
    }
}
