//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buses.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Routes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public A_Routes()
        {
            this.A_Buses = new HashSet<A_Buses>();
        }
    
        public int Route_ID { get; set; }
        public string Route_Name { get; set; }
        public string Start_Stage { get; set; }
        public string Destination_Stage { get; set; }
        public string Route_Description { get; set; }
        public Nullable<int> Company { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A_Buses> A_Buses { get; set; }
        public virtual A_Companies A_Companies { get; set; }
    }
}
