//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buses.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus_Scheduling
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bus_Scheduling()
        {
            this.Online_Ticketing = new HashSet<Online_Ticketing>();
            this.Customer_Booking = new HashSet<Customer_Booking>();
            this.Stage_Ticketing = new HashSet<Stage_Ticketing>();
        }
    
        public int ID { get; set; }
        public int Bus_ID { get; set; }
        public System.DateTime Departure_Time { get; set; }
        public Nullable<int> Status_ID { get; set; }
        public Nullable<System.DateTime> Arrival_Time { get; set; }
        public Nullable<int> Company_ID { get; set; }
        public Nullable<System.DateTime> Boarding_Time { get; set; }
    
        public virtual A_Buses A_Buses { get; set; }
        public virtual A_Companies A_Companies { get; set; }
        public virtual A_Schedule_Status A_Schedule_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Online_Ticketing> Online_Ticketing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_Booking> Customer_Booking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stage_Ticketing> Stage_Ticketing { get; set; }
    }
}
