//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buses.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bus_Ticketing_SystemEntities : DbContext
    {
        public Bus_Ticketing_SystemEntities()
            : base("name=Bus_Ticketing_SystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<A_Buses> A_Buses { get; set; }
        public virtual DbSet<A_Companies> A_Companies { get; set; }
        public virtual DbSet<A_Contact_Type> A_Contact_Type { get; set; }
        public virtual DbSet<A_Country> A_Country { get; set; }
        public virtual DbSet<A_Customer> A_Customer { get; set; }
        public virtual DbSet<A_Employees> A_Employees { get; set; }
        public virtual DbSet<A_Gender> A_Gender { get; set; }
        public virtual DbSet<A_Level_Of_Education> A_Level_Of_Education { get; set; }
        public virtual DbSet<A_Manufacturer> A_Manufacturer { get; set; }
        public virtual DbSet<A_Personel_Titles> A_Personel_Titles { get; set; }
        public virtual DbSet<A_Schedule_Status> A_Schedule_Status { get; set; }
        public virtual DbSet<Customer_Booking> Customer_Booking { get; set; }
        public virtual DbSet<CustomerNOK> CustomerNOKs { get; set; }
        public virtual DbSet<Employee_NOK> Employee_NOK { get; set; }
        public virtual DbSet<Online_Ticketing> Online_Ticketing { get; set; }
        public virtual DbSet<Education> Educations { get; set; }
        public virtual DbSet<View_Employee_Education> View_Employee_Education { get; set; }
        public virtual DbSet<A_Routes> A_Routes { get; set; }
        public virtual DbSet<Bus_Scheduling> Bus_Scheduling { get; set; }
        public virtual DbSet<Stage_Ticketing> Stage_Ticketing { get; set; }
        public virtual DbSet<View_Scheduling> View_Scheduling { get; set; }
        public virtual DbSet<View_Stage_Booking> View_Stage_Booking { get; set; }
        public virtual DbSet<View_Stage_Booking_Final> View_Stage_Booking_Final { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<View_Users> View_Users { get; set; }
    }
}
