//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buses.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public int Id { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Level_Of_Education { get; set; }
        public string Grade { get; set; }
        public byte[] Certificate { get; set; }
        public string School { get; set; }
        public Nullable<int> Start_Year { get; set; }
        public Nullable<int> End_Year { get; set; }
    
        public virtual A_Employees A_Employees { get; set; }
        public virtual A_Level_Of_Education A_Level_Of_Education { get; set; }
    }
}
