//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buses.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Online_Ticketing
    {
        public string Ticket_No { get; set; }
        public Nullable<int> Schedule_ID { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> Customer_ID { get; set; }
    
        public virtual A_Customer A_Customer { get; set; }
        public virtual Bus_Scheduling Bus_Scheduling { get; set; }
    }
}
