//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buses.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Users
    {
        public string UserId { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string UserName { get; set; }
        public Nullable<int> Bus_Id { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public string RoleId { get; set; }
        public string Role_Desc { get; set; }
        public string Company_Name { get; set; }
        public string CountryCode { get; set; }
    }
}
