//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buses.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Stage_Booking
    {
        public string Ticket_No { get; set; }
        public Nullable<int> Schedule_ID { get; set; }
        public System.DateTime Departure_Time { get; set; }
        public Nullable<System.DateTime> Arrival_Time { get; set; }
        public int Bus_ID { get; set; }
        public string Plate_No { get; set; }
        public Nullable<int> Seat_No { get; set; }
        public int Route_ID { get; set; }
        public string Route_Name { get; set; }
        public string Start_Stage { get; set; }
        public string Destination_Stage { get; set; }
        public int Status_ID { get; set; }
        public string Status_Desc { get; set; }
        public int ID { get; set; }
        public string Companies_Name { get; set; }
        public string Location { get; set; }
        public string CountryCode { get; set; }
        public Nullable<int> Driver_ID { get; set; }
        public string Employees_Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Gender { get; set; }
        public string Gender_Desc { get; set; }
        public string Nationality { get; set; }
        public string CountryName { get; set; }
        public Nullable<System.DateTime> Boarding_Time { get; set; }
    }
}
